dnnlib: Running training.training_loop.training_loop() on localhost...
Streaming data using training.dataset.TFRecordDataset...
Dataset shape = [3, 128, 128]
Dynamic range = [0, 255]
Label size    = 0
Constructing networks...
Traceback (most recent call last):
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation G_synthesis/lod: {{node G_synthesis/lod}} was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
	 [[G_synthesis/lod]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 191, in <module>
    main()
  File "train.py", line 186, in main
    dnnlib.submit_run(**kwargs)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/submission/submit.py", line 290, in submit_run
    run_wrapper(submit_config)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/submission/submit.py", line 242, in run_wrapper
    util.call_func_by_name(func_name=submit_config.run_func_name, submit_config=submit_config, **submit_config.run_func_kwargs)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/util.py", line 257, in call_func_by_name
    return func_obj(*args, **kwargs)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/training/training_loop.py", line 156, in training_loop
    G = tflib.Network('G', num_channels=training_set.shape[0], resolution=training_set.shape[1], label_size=training_set.label_size, **G_args)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/tflib/network.py", line 98, in __init__
    self._init_graph()
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/tflib/network.py", line 155, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/training/networks_stylegan.py", line 334, in G_style
    components.synthesis = tflib.Network('G_synthesis', func_name=G_synthesis, **kwargs)
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/tflib/network.py", line 99, in __init__
    self.reset_own_vars()
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/tflib/network.py", line 190, in reset_own_vars
    tfutil.run([var.initializer for var in self.own_vars.values()])
  File "/home/vignesh_pagadala/Desktop/GAN_2/stylegan-master/dnnlib/tflib/tfutil.py", line 26, in run
    return tf.get_default_session().run(*args, **kwargs)
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation G_synthesis/lod: node G_synthesis/lod (defined at /home/vignesh_pagadala/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748)  was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
	 [[G_synthesis/lod]]
